# fly.toml file generated for strava-distance-search on 2022-11-20T16:25:44-05:00

app = "strava-distance-search"
kill_signal = "SIGINT"
kill_timeout = 5

[deploy]
  release_command = "python manage.py migrate --noinput"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
