name: Tests
on: [push]
jobs:
  Run-Django-Tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: 'distance_search.settings.local'
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: Test
        run: |
          pipenv run python manage.py test

